### ISSUE TITLE
mist.groupToPoint documentation mentions undocumented "random distance"

### ISSUE THREAD

**Issue by birgersp** [mrSkortch/MissionScriptingTools#31]
From the mist.groupToPoint documentation:
> ... point can be a zoneTable or zoneName. If not specified a
random distance between 300 and 1000 meters will be defined.  form is the def ...

This "random distance" should be documented, is it computing a random point from the point specified (by som radius)?

I'd fix it myself but I don't have Microsoft Office at home

**Comment by red15** [comment]
Did you check if the wiki also has this bug?
And it's a wiki so you can easily correct it there.

**Comment by birgersp** [comment]
Yes, [the wiki](http://wiki.hoggit.us/view/GroupToPoint) has the same error. I couldn't register for the wiki before (something with the server I guess) but today it worked. Once (if) I get my user account approved I will fix the wiki. I guess it should just be removed so it will say:

`... group can be either a group name or a group table. point can be a zoneTable or zoneName. form is the default ...`

I won't touch the .doc file though. The documentation shouldn't really be manually mirrored like this (with the wiki vs. the .doc). Also, in my personal opinion (don't mean to be rude here), a binary file like this should not be a part of a software repository.

**Comment by mrSkortch** [comment]
The doc file is there as an old hold-over from the time before the wiki and later github pages were created. Its still updated mostly so there is an offline reference available just in case the wiki is down. The primary source of information should be the wiki though.

**Comment by birgersp** [comment]
Okay, sorry I didn't fix the wiki. I never got my account approved... Thanks!

**Comment by mrSkortch** [comment]
I fixed it on both. I'll have to ask the guy who runs the wiki about the account, but you can still make edits without logging in.
