### ISSUE TITLE
I believe that mist.getNextUnitId() is broken at the moment. (with 1.5.5)

### ISSUE THREAD

**Issue by afinegan** [mrSkortch/MissionScriptingTools#35]
mist.getNextUnitId() keeps giving me the number "14000" over and over, I did a quick and dirty replacement by putting in math.random(100000000,200000000) for _unitId in CTLD and it worked.

What was happening is I was spawning crates. and everytime I respawn the same crate the previous one dissappeared, this is due to the ID being the same number

**Comment by mrSkortch** [comment]
So it turns out I did something incredibly stupid with that function. Fixed in build 76. Should be on development branch soonish.
