### ISSUE TITLE
mist.removeFunction should return boolean true when function is removed

### ISSUE THREAD

**Issue by walder** [mrSkortch/MissionScriptingTools#48]
The current implementation does not return anything, despite the docs saying so:
```lua
	--- Removes a scheduled function.
	-- @tparam number id function id
	-- @treturn boolean true if function was successfully removed, false otherwise.
	function mist.removeFunction(id)
		local i = 1
		while i <= #scheduledTasks do
			if scheduledTasks[i].id == id then
				table.remove(scheduledTasks, i)
			else
				i = i + 1
			end
		end
	end


```
The function should look like this:
```lua
	--- Removes a scheduled function.
	-- @tparam number id function id
	-- @treturn boolean true if function was successfully removed, false otherwise.
	function mist.removeFunction(id)
		local i = 1
		local removedFunction = false
		while i <= #scheduledTasks do
			if scheduledTasks[i].id == id then
				table.remove(scheduledTasks, i)
				removedFunction = true
			else
				i = i + 1
			end
		end
		return removedFunction
	end
```

**Comment by walder** [comment]
> The current implementation does not return anything, despite the docs saying so:
> 	--- Removes a scheduled function.
> 	-- @tparam number id function id
> 	-- @treturn boolean true if function was successfully removed, false otherwise.
> 	function mist.removeFunction(id)
> 		local i = 1
> 		while i <= #scheduledTasks do
> 			if scheduledTasks[i].id == id then
> 				table.remove(scheduledTasks, i)
> 			else
> 				i = i + 1
> 			end
> 		end
> 	end
> 
> 
> The function should look like this:
> 	--- Removes a scheduled function.
> 	-- @tparam number id function id
> 	-- @treturn boolean true if function was successfully removed, false otherwise.
> 	function mist.removeFunction(id)
> 		local i = 1
> 		local removedFunction = false
> 		while i <= #scheduledTasks do
> 			if scheduledTasks[i].id == id then
> 				table.remove(scheduledTasks, i)
> 				removedFunction = true
> 			else
> 				i = i + 1
> 			end
> 		end
> 		return removedFunction
> 	end
> Also I'm not quite sure if the i = i + 1 should be in the else block. It would skip iteration if the task is found, why? A break in the if condition would make more sense?

**Comment by mrSkortch** [comment]
https://github.com/mrSkortch/MissionScriptingTools/commit/de4b4e0d0d70d021d1acfe9c68feef4498d381cf

Fixed.
