### ISSUE TITLE
mist.getUnitsInPolygon errors v4.3.74

### ISSUE THREAD

**Issue by beaglewrangler** [mrSkortch/MissionScriptingTools#50]
When called, this produced two errors that I managed to troubleshoot and resolve so it worked for me as intended.

1. the first parameter is called **unit_names** but **unitNames** is referenced in the body.

2. an error that you are trying to do arithmetic on a table is shown, caused on line 2520:
inZoneUnits[inZoneUnits + 1] = units[i]

I fixed it by changing it to:

inZoneUnits[#inZoneUnits + 1] = units[i]

Thanks

**Comment by mrSkortch** [comment]
This has been fixed.
