### ISSUE TITLE
please add neutral group

### ISSUE THREAD

**Issue by Jagohu** [mrSkortch/MissionScriptingTools#54]
Please add to line 126 if you don't mind and perhaps to other tables as well, so neutral units can be handled. Thank you!
`if (coa_name == 'red' or coa_name == 'blue' or coa_name == 'neutrals') and type(coa_data) == 'table' then`

**Comment by mrSkortch** [comment]
Been meaning to. I added it for slmod but hadn't gotten around to it in mist. Done

https://github.com/mrSkortch/MissionScriptingTools/commit/5e26588a91c90e39d86c7bb7a5add286df696a32
