### ISSUE TITLE
mist.flagFunc.mapobjs_dead_zones not working in later DCS

### ISSUE THREAD

**Issue by JohnnyJohnnySE** [mrSkortch/MissionScriptingTools#57]
So I was fiddling around in Mission editor and wanted to do a mission where I destroy a bridge. However using mist.flagFunc.mapobjs_dead_zones just returns error when used and callback seems to be empty or blank. 

To investigate further I loaded up a old mission basedon MIST 4.3 that previously worked and ran it, but it just craps out when activated. So something has changed in DCS later releases, using latest open beta. 

Codesnip I used was
mist.flagFunc.mapobjs_dead_zones{  
   zones = {'BridgeZone'},  
   flag = 10
}

![image](https://user-images.githubusercontent.com/64427820/101184317-de4ffe00-3650-11eb-8bcb-97b8299258ff.png)

**Comment by mrSkortch** [comment]
That error means that mist isn't loading. Try updating to a newer version of mist since there were issues caused by DCS updates. Also check your dcs.log to make sure mist is loading. It could be the trigger that is failing or executing before mist is loaded.

**Comment by JohnnyJohnnySE** [comment]
Redid my triggers and still had issue, but implemented different logic in them and retried , then it worked, so not a bug or issue, closing :)
