### ISSUE TITLE
Potential Typo issue - line 3610 of v4_5_99

### ISSUE THREAD

**Issue by coSjuju** [mrSkortch/MissionScriptingTools#62]
As in title, _**Tarrain**_ instead of _**Terrain**_ :

        local validTerrain = {'LAND', 'ROAD', 'SHALLOW_WATER', 'WATER', 'RUNWAY'}
        if vars.anyTarrain then
            -- do nothing

**Comment by mrSkortch** [comment]
Yeah that is a typo. Thanks for the heads up.
