### ISSUE TITLE
Invisible FARPs render getUnitsInZones non working

### ISSUE THREAD

**Issue by spencershepard** [mrSkortch/MissionScriptingTools#64]
mist_4_4_90.lua"]:2652: attempt to call method 'isActive' (a nil value)

mist.getUnitsInZones(mist.makeUnitTable({'[all]'}), {'Alpha_Zone'})

**Comment by mrSkortch** [comment]
That was fixed a long time ago: 
7829d380b0be09159d5bd183b4c8a593a19c7cbf

I swear I will try to merge development build into master soon.
