### ISSUE TITLE
Specifying string name does not work after latest DCS update

### ISSUE THREAD

**Issue by ucnanoman** [mrSkortch/MissionScriptingTools#69]
Here are more details, I used the two latest versions of MIST, can't get it to work.
Was working a long time (it's a CSAR POW Mod for DCS that I added using MIST)

**Line that Errors out:**

POW1MARKER.pos = Unit.getByName("NameOfUnit"):getPoint()         -- This is the line that errored out, used to work
or
POW1MARKER.pos = Group.getByName("NameOfUnit"):getPoint()      -- This is the line that errored out, used to work

I narrowed my error to this last line above either of the two.

**Error from dcs.log:**
2022-08-14 04:56:46.250 ERROR   SCRIPTING: Error while handling event [string "C:\Users\username\AppData\Local\Temp\DCS.openbeta\/~mis00003EE0.lua"]:1060: attempt to index a nil value

**Full Code Sample:**

```
----create a orange marker for POW when released!
local myLog = mist.Logger:new('PRISONLOG')
POW1MARKER = {} ---this table is instantiated at the top of the code
csar.enableCSAROrangeCircles = True
csar.enableCSARForVIP = True
if csar.enableCSAROrangeCircles then	
     if csar.enableCSARForVIP then
           myLog:msg("D1")	
           POW1MARKER.pos = Unit.getByName("POW1"):getPoint() -- this is the line that errors out, worked b4
	   --POW1MARKER.pos = _unit.getByName("POW1"):getPoint() -- tried this as well, doesn't work  
           --POW1MARKER.pos = _unit:getByName("POW1"):getPoint() -- tried this as well, doesn't work  	    
           --POW1MARKER.pos = Group.getByName("POW1"):getPoint() -- tried this as well, doesn't work                  
           myLog:msg("D2")	
           POW1MARKER.id = mist.marker.getNextId()
           myLog:msg("D3")	
           POW1MARKER.mType = 0
           myLog:msg("D4")	
           POW1MARKER.readOnly = 0
           myLog:msg("D5")	
           POW1MARKER.text = "POW1 Located Here!"
           myLog:msg("D6")	
           mist.marker.add(POW1MARKER)
           myLog:msg("D7")	
           POW1MARK_check = "YES"
           myLog:msg("D8")	
           POW1DEAD_check = "YES"  
           myLog:msg("D9")	              
     end
end

myLog:msg("E")
```

**dcs.log file messages:**
2022-08-14 04:56:46.250 INFO    SCRIPTING: PRISONLOG|1056: D1
2022-08-14 04:56:46.250 ERROR   SCRIPTING: Error while handling event [string "C:\Users\username\AppData\Local\Temp\DCS.openbeta\/~mis00003EE0.lua"]:1060: attempt to index a nil value

**Comment by mrSkortch** [comment]
It is literally impossible for me to figure out the problem without more context. Full sample of what you are passing to whichever function is apparently buggy.

**Comment by ucnanoman** [comment]
I'm sorry to post only the line, hopefully this above give you a clear picture of my error, let me know how else I can explain it.

**Comment by mrSkortch** [comment]
Ok, so it is erroring on your code. I guess the obvious question is if there is a unit in the mission actually named "POW1"? Otherwise yeah it would error because you are using getPoint() on a nil object. Whenever you are getting an object it is a good idea to verify it actually exists before trying to do anything to it. 

```
local u = Unit.getByName("POW1")
if u then
  POW1MARKER.pos = u:getPoint()
else
  myLog:msg("POW1 didnt exist")
end
```

**Comment by ucnanoman** [comment]
![image](https://user-images.githubusercontent.com/61528637/184527162-406d5c57-0e03-4c6f-8502-8c80aab81534.png)

**Comment by ucnanoman** [comment]
I see what you're saying, yea definitely have POW1 in the unit name.
POW1 is group name as well and have tried it without putting POW1 as the group name as well.
Still errors.

**Comment by ucnanoman** [comment]
This is actually a different issue than what I thought ... really it's marker.pos that cannot receive a point(). I'll open up another issue for it.
