### ISSUE TITLE
Unable to remove a line 

### ISSUE THREAD

**Issue by flasher44** [mrSkortch/MissionScriptingTools#90]
Mission2= mist.marker.drawShape('ellypse')  => working
mist.marker.remove(Mission2) => working with polygons

Mission1= mist.marker.drawShape('line')  => working
mist.marker.remove(Mission1) => not working with a line

**Comment by mrSkortch** [comment]
Fixed in: 
https://github.com/mrSkortch/MissionScriptingTools/commit/e01bfd25d5761cb9810628da558a958fcb201cb1
