### ISSUE TITLE
"Object doesn't exist" error when destroying Oil Well and Gas Platform statics

### ISSUE THREAD

**Issue by TS-Coles** [mrSkortch/MissionScriptingTools#91]
![image](https://github.com/mrSkortch/MissionScriptingTools/assets/160782010/81a424df-a21f-4d7e-92dd-16accff2443a)

Steps to reproduce:
mist_4_5_122.lua is in use
Oil well or Gas platform static object is killed

Error on line 1546 when calling Object.getPosition in function addDeadObject

[MIST_scripting_error_miz.zip](https://github.com/mrSkortch/MissionScriptingTools/files/14364212/MIST_scripting_error_miz.zip)

**Comment by mrSkortch** [comment]
That appears to partially be a DCS bug. Few functions are working when those two objects get killed. Fixed it in mist https://github.com/mrSkortch/MissionScriptingTools/commit/e01bfd25d5761cb9810628da558a958fcb201cb1 but I will need ED to fix the base of the problem too.
