### ISSUE TITLE
mist.RespawnGroup no longer working on ground units

### ISSUE THREAD

**Issue by arktosTM1** [mrSkortch/MissionScriptingTools#93]
One of the recent DCS updates has broken the functionality of 'mist.respawnGroup' on ground units in my missions, only. Air units respawn normally. Script reference: 
  
  `if not
  Group.getByName('GROUP')
  then
  
  mist.respawnGroup('GROUP', true)
  end`

Thank you for the great tool, happy to provide any more information as needed.

**Comment by mrSkortch** [comment]
Add a debug line in there to verify it is trying to run mist.respawnGroup. For example just before mist.respawnGroup add an env.info("respawn") and see if it shows up in the dcs.log. 

Alternatively try 

`
if mist.groupIsDead("GROUP") then
   mist.respawnGroup("GROUP", true)
end
`
It is possible that simply checking if the group exists via if not Group.getByName("whatever") is enough.

**Comment by mrSkortch** [comment]
Try: https://github.com/mrSkortch/MissionScriptingTools/blob/master/mist_4_5_126.lua

DCS re-introduced a bug which impacted mist.groupIsDead

**Comment by tsmcc** [comment]
mrSkortch - this worked! many thanks, and thanks again for the quick communication. VERY excited to get back in the mission with friends.
